# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scrapyd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True, verbose_name='部署平台名称')),
                ('ip', models.CharField(max_length=45, verbose_name='IP')),
                ('port', models.CharField(max_length=45, verbose_name='端口')),
                ('comment', models.CharField(blank=True, max_length=128, null=True, verbose_name='简介')),
            ],
        ),
    ]
