# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='项目名称')),
                ('comment', models.CharField(blank=True, max_length=128, null=True, verbose_name='简介')),
                ('scrapyd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Scrapyd')),
            ],
        ),
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='爬虫名称')),
                ('comment', models.CharField(blank=True, max_length=128, null=True, verbose_name='简介')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Project')),
            ],
        ),
    ]
