# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='分组名称')),
                ('comment', models.CharField(blank=True, max_length=128, null=True, verbose_name='简介')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='项目名称')),
                ('comment', models.CharField(blank=True, max_length=128, null=True, verbose_name='简介')),
            ],
        ),
        migrations.CreateModel(
            name='Scrapyd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True, verbose_name='部署平台名称')),
                ('ip', models.CharField(max_length=45, verbose_name='IP')),
                ('port', models.CharField(max_length=45, verbose_name='端口')),
                ('comment', models.CharField(blank=True, max_length=128, null=True, verbose_name='简介')),
            ],
        ),
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='爬虫名称')),
                ('comment', models.CharField(blank=True, max_length=128, null=True, verbose_name='简介')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapyinfo.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='scrapyd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapyinfo.Scrapyd'),
        ),
        migrations.AddField(
            model_name='group',
            name='spider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapyinfo.Spider'),
        ),
    ]
